### ISSUE TITLE
 ID internal-source-marker_0.15xxx already defined in Entity, line: 2

### ISSUE THREAD

**Issue by elabayoub** [ezsystems/ezplatform-xmltext-fieldtype#29]
Hi,
I get this error everytime i run the script:

`[Symfony\Component\Debug\Exception\ContextErrorException]
  Warning: DOMDocument::loadXML(): ID internal-source-marker_0.15xxxx already defined in Entity, line: 2
`

Thanks

**Comment by elabayoub** [comment]
In my case the error was showing because an record in database(table’ table_xxx’-> field_xx) it’s xml content contains many tags(nodes) with same ID. So i deleted it and this won’t affect anything because the record was there for the framework demo test page.

**Comment by andrerom** [comment]
@elabayoub returning to this topic now, this was also `id` property like in #27 right? If so we can close this one, and post an example of your XMLText in the other issue.

**Comment by vidarl** [comment]
If I don't get feedback on this one in a few days, I'll close it as a dupe of #27

**Comment by vidarl** [comment]
Closing, probably a duplicate of #27
