### ISSUE TITLE
RichText: conversion and validation from Legacy ezxml involving temporary paragraphs

### ISSUE THREAD

**Issue by andrerom** [ezsystems/ezplatform-xmltext-fieldtype#35]
> In ~EZP-24710~ it was reported that ezxmltext datatype in Legacy Stack will not create temporary namespace attributes on temporary paragraphs when Online Editor is disabled. That issue reports the problem with rendered output with XmlText, but the same problem causes issues with RichText's ezxml -> docbook conversion.
> 
> In that case converter will not remove temporary paragraphs as it expects them to be properly marked, resulting in nested paragraphs, like <para><para>...</para></para>.
> 
> Additionally, the schema of RichText's internal format (docbook) allows for that, so it also needs to be fixed.

Original JIRA issue: https://jira.ez.no/browse/EZP-24968

**Comment by andrerom** [comment]
Related: 
> RichText: to legacy EZXML conversion does not preserve local tmp paragraph namespaces
https://jira.ez.no/browse/EZP-23646
WIP PR https://github.com/ezsystems/ezpublish-kernel/pull/1092

**Comment by vidarl** [comment]
This issue has been fixed and merged ( pending QA though )
