### ISSUE TITLE
Could not find 'user' with identifier 'admin'

### ISSUE THREAD

**Issue by xrowdominik** [ezsystems/ezplatform-xmltext-fieldtype#57]
If I execute the command:  `bin/console ezxmltext:convert-to-richtext --dry-run` I´m getting the error that there is no user with identifier admin. This is in my case true, because we have no user called 'admin' in our database. If I change the user in the code to our admin user the command works. 
There should be an option to set the admin user. 
Or am I doing something wrong here?

Line in code:  https://github.com/ezsystems/ezplatform-xmltext-fieldtype/blob/master/bundle/Command/ConvertXmlTextToRichTextCommand.php#L211

**Comment by andrerom** [comment]
This is a general issue for all commands that need admin user, so I suggest this is reported as feature request on eZ Platform.

**Comment by andrerom** [comment]
That said, such a feature can take a while.
Maybe just port over this form other commands that have support for this. WDYT @natanael89 ?

**Comment by natanael89** [comment]
Sure, that's a good idea. Example from our codebase: https://github.com/ezsystems/ezpublish-kernel/blob/11e7a1e04464918189331510df0baa197040f6a5/eZ/Bundle/EzPublishCoreBundle/Command/CheckURLsCommand.php#L39 and https://github.com/ezsystems/ezpublish-kernel/blob/11e7a1e04464918189331510df0baa197040f6a5/eZ/Bundle/EzPublishCoreBundle/Command/CheckURLsCommand.php#L55

**Comment by vidarl** [comment]
I have created issue in jira : https://jira.ez.no/browse/EZP-29487

I am closing the issue here. Please follow jira issue for further info
